### ISSUE TITLE
Feedback Request: LNX2

### ISSUE THREAD

**Issue by se0727** [TechGrounds-Cloud8/cloud8-se0727#4]
**Feedback Request LNX2
Permalink to file: [LNX2](https://github.com/TechGrounds-Cloud8/cloud8-se0727/blob/main/01_Fundamentals_1/LNX-02%20FileDir.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Tjomba1996** [comment]
- Termen niet uitgelegd
- Results kunnen wat uitleg gebruiken.
- Links even uit elkaar trekken
- u > you

- Antwoorden niet niet helemaal correct. Geen permissies laten zien. En geen absolute of relative pathing laten zien.

**Comment by Killian97** [comment]
ik kan niet vinden of je relative en absolute pathing begrijpt. voor de rest ziet wel alles er begrepen uit. alleen de layout wel
